# fly.toml app configuration file generated for application-ktor on 2024-06-13T22:23:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'application-ktor'
primary_region = 'gru'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[env]
TZ = "America/Sao_Paulo"
